### register errol
POST  http://localhost:5000/user HTTP/1.1
content-type: application/json

{
    "name": "errol",
    "email": "errol@gmail.com",
    "password": "123456"
}
### register mickey
POST  http://localhost:5000/user HTTP/1.1
content-type: application/json

{
    "name": "mickey",
    "email": "mickey@gmail.com",
    "password": "123456"
}

### sign in errol
POST  http://localhost:5000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "errol@gmail.com",
    "password": "123456"
}

### sign in roops
POST  http://localhost:5000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "r@r.com",
    "password": "roopss"
}

### logout user
DELETE   http://localhost:5000/auth/logout HTTP/1.1
content-type: application/json


### private route test
GET  http://localhost:5000/private HTTP/1.1
content-type: application/json


### home test
GET  http://localhost:5000/ HTTP/1.1
content-type: application/json

### authenticate test
GET  http://localhost:5000/auth/isauth HTTP/1.1
content-type: application/json

### register test
POST   http://localhost:5000/user HTTP/1.1
content-type: application/json


### LISTS

### view lists
GET   http://localhost:5000/list HTTP/1.1
content-type: application/json


### create list
POST   http://localhost:5000/list HTTP/1.1
content-type: application/json

{
    "name":"errols ultra list"
}

### get single list
GET    http://localhost:5000/list/5e8baa4802ddbe3b648cc1af HTTP/1.1
content-type: application/json

### update name of list
PATCH http://localhost:5000/list/5e8baa4802ddbe3b648cc1af HTTP/1.1
content-type: application/json

{
    "name":"edited lists"
}

### create list item
PATCH http://localhost:5000/list/5e8baa4802ddbe3b648cc1af HTTP/1.1
content-type: application/json

{
    "item":{
        "done":false,
        "text":"bye"
    }
}

### edit list item by passing _id
PATCH http://localhost:5000/list/5e8baa4802ddbe3b648cc1af HTTP/1.1
content-type: application/json

{
    "item":{
        "_id":"5e8baa9b02ddbe3b648cc1b2",
        "done":false,
        "text":"ballooooon"
    }
}