
// register a user

POST  http://localhost:5000/user HTTP/1.1
content-type: application/json

{
    "name": "errol",
    "email": "errol@gmail.com",
    "password": "123456"
}

###
// sign in user

POST  http://localhost:5000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "errol@gmail.com",
    "password": "123456"
}
