### register errol
POST  http://localhost:5000/user HTTP/1.1
content-type: application/json

{
    "name": "errol",
    "email": "errol@gmail.com",
    "password": "123456"
}

### register don
POST  http://localhost:5000/user HTTP/1.1
content-type: application/json

{
    "name": "",
    "email": "don@",
    "password": "12456"
}
### register mickey
POST  http://localhost:5000/user HTTP/1.1
content-type: application/json

{
    "name": "mickey",
    "email": "mickey@gmail.com",
    "password": "123456"
}

### sign in errol
POST  http://localhost:5000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "errol@gmail.com",
    "password": "123456"
}

### sign in roops
POST  http://localhost:5000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "r@r.com",
    "password": "roopss"
}

### logout user
DELETE   http://localhost:5000/auth/logout HTTP/1.1
content-type: application/json


### private route test
GET  http://localhost:5000/private HTTP/1.1
content-type: application/json


### home test
GET  http://localhost:5000/ HTTP/1.1
content-type: application/json

### authenticate test
GET  http://localhost:5000/auth/isauth HTTP/1.1
content-type: application/json

### register test
POST   http://localhost:5000/user HTTP/1.1
content-type: application/json


### LISTS

### view lists
GET   http://localhost:5000/list HTTP/1.1
content-type: application/json


### create list
POST   http://localhost:5000/list HTTP/1.1
content-type: application/json

{
    "name":"errols gh list"
}

### get single list
GET    http://localhost:5000/list/5e8e2a23cdb7fc4b3c72cf94 HTTP/1.1
content-type: application/json

### update name of list
PATCH http://localhost:5000/list/5e8baa4802ddbe3b648cc1af HTTP/1.1
content-type: application/json

{
    "name":"edited lists"
}

### create list item
POST http://localhost:5000/list/5e8e2a23cdb7fc4b3c72cf94/item HTTP/1.1
content-type: application/json

{
        "text":"hey micket"
}

### edit list item by passing _id
PATCH http://localhost:5000/list/5e8baa5002ddbe3b648cc1b0/item/5e8e0e3b789afc0534418768 HTTP/1.1
content-type: application/json

{   
        "_id":"5e8e0e3b789afc0534418768",
        "done":false,
        "text":"errols five"
}

### delete list by passing id
DELETE  http://localhost:5000/list/5e8c9f8c3edfad0a987bdd73 HTTP/1.1
content-type: application/json

{
    "_id":"5e8c9f8c3edfad0a987bdd73"    
}

### delete item by passing item id
DELETE  http://localhost:5000/list/5e8e2a23cdb7fc4b3c72cf94/item/5e8e2a39cdb7fc4b3c72cf96 HTTP/1.1
content-type: application/json

{
        "_id":"5e8e2a39cdb7fc4b3c72cf96"
}
